### ISSUE TITLE
SetBackground Image Size

### ISSUE THREAD

**Issue by khadka7** [lionix-team/vue-image-markup#2]
when large size of image is upload it does not render all in background.
How to fill whole image in background.
Example when i upload the image of (1500*2000) due to canvas height and width image cannot be render fully.
How to fix this ?

**Comment by lilitsimonyan98** [comment]
I have pushed a new release, where that issue have been fixed. 
Please upload the new version.

**Comment by PeteyRev** [comment]
@lilitsimonyan98 This is still happening to me version 2.0.7. Image is 2000 x 1800

**Comment by burczu** [comment]
it still doesn't work... version 3.1.3

**Comment by MarkCondello** [comment]
I can also confirm that the setBackgroundImage() method does not work.
Any change / updates on this yet? 
I'm using "vue-image-markup": "^3.2.0"
